services:
  game_server:
    platform: linux/x86_64
    build:
      dockerfile: build/server/Dockerfile
      target: final
    ports:
      - 19000:9000
    depends_on:
      authentication:
        condition: service_started

  authentication:
    build:
      context: authentication
      target: final
    secrets:
      - db-password
      - identity-secret
      - identity-refresh-secret
      - server-oauth-client-id
      - server-oauth-client-secret
      - steam-web-api-key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      IDENTITY_SECRET_FILE: /run/secrets/identity-secret
      IDENTITY_EXPIRES_IN_SECS: 3600
      REFRESH_SECRET_FILE: /run/secrets/identity-refresh-secret
      REFRESH_EXPIRES_IN_DAYS: 7
      ALLOWED_ORIGINS: "http://localhost:8060,https://multiplayer-test.bryanmylee.com"
      OAUTH_CLIENT_ID_FILE: /run/secrets/server-oauth-client-id
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/server-oauth-client-secret
      STEAM_APP_ID: 2843770
      STEAM_WEB_API_KEY_FILE: /run/secrets/steam-web-api-key
    ports:
      - 18000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db-password.txt
  identity-secret:
    file: secrets/identity-secret.txt
  identity-refresh-secret:
    file: secrets/identity-refresh-secret.txt
  server-oauth-client-id:
    file: secrets/server-oauth-client-id.txt
  server-oauth-client-secret:
    file: secrets/server-oauth-client-secret.txt
  steam-web-api-key:
    file: secrets/steam-web-api-key.txt
