services:
  web-client:
    platform: linux/amd64
    image: bryanmylee/multiplayer-base-web-client
    build:
      dockerfile: build/web/Dockerfile
    ports:
      - 10443:9000

  game-server:
    platform: linux/amd64
    image: bryanmylee/multiplayer-base-game-server
    build:
      dockerfile: build/server/Dockerfile
      target: final
    ports:
      - 19000:9000
    depends_on:
      authentication:
        condition: service_started

  authentication:
    platform: linux/amd64
    image: bryanmylee/multiplayer-base-authentication
    build:
      context: authentication
      target: final
    secrets:
      - db-url
      - identity-secret
      - identity-refresh-secret
      - server-oauth-client-id
      - server-oauth-client-secret
      - steam-web-api-key
    environment:
      POSTGRES_URL_FILE: /run/secrets/db-url
      IDENTITY_SECRET_FILE: /run/secrets/identity-secret
      IDENTITY_EXPIRES_IN_SECS: 3600
      REFRESH_SECRET_FILE: /run/secrets/identity-refresh-secret
      REFRESH_EXPIRES_IN_DAYS: 7
      ALLOWED_ORIGINS: "http://localhost:8060,https://multiplayer-base.bryanmylee.com"
      OAUTH_CLIENT_ID_FILE: /run/secrets/server-oauth-client-id
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/server-oauth-client-secret
      STEAM_APP_ID: 2843770
      STEAM_WEB_API_KEY_FILE: /run/secrets/steam-web-api-key
    ports:
      - 18000:8000

secrets:
  db-url:
    file: secrets/db-url.txt
  identity-secret:
    file: secrets/identity-secret.txt
  identity-refresh-secret:
    file: secrets/identity-refresh-secret.txt
  server-oauth-client-id:
    file: secrets/server-oauth-client-id.txt
  server-oauth-client-secret:
    file: secrets/server-oauth-client-secret.txt
  steam-web-api-key:
    file: secrets/steam-web-api-key.txt
