[package]
name = "game-server-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
dotenvy = "0.15.7"
env_logger = "0.11.1"
lazy_static = "1.4.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
